
USE ROLE YelpAdmin_ROLE;
USE WAREHOUSE Yelp_WH;
USE DATABASE Yelp_DB;
USE SCHEMA YELP_BUSINESS;

CREATE OR REPLACE TABLE YELP_DB.YELP_BUSINESS.YELP_BUSINESS (
	BUSINESS_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR,
    STATE VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    LATITUTE FLOAT,
    LONGITUDE FLOAT,
    STARS FLOAT,
    REVIEW_COUNT INTEGER,
    IS_OPEN INTEGER,
    CATEGORIES VARCHAR(255),
    LOAD_DATETIME TIMESTAMP_LTZ
);