
USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE YelpAdmin_ROLE;

GRANT ROLE YelpAdmin_ROLE TO ROLE SYSADMIN;
GRANT ROLE YelpAdmin_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE YelpAdmin_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE YelpAdmin_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE YelpAdmin_ROLE;

-- GRANT WRITE PRIVILEGES ON DATABASE OAG_FLIGHT_STATUS_DATA_SAMPLE TO ROLE Flight_ROLE;




-- Databases
CREATE OR REPLACE DATABASE Yelp_DB;
GRANT OWNERSHIP ON DATABASE Yelp_DB TO ROLE YelpAdmin_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE Yelp_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE Yelp_WH TO ROLE YelpAdmin_ROLE;


-- Use
USE ROLE YelpAdmin_ROLE;
USE WAREHOUSE Yelp_WH;
USE DATABASE Yelp_DB;


-- Schemas
CREATE OR REPLACE SCHEMA Yelp_Business;
CREATE OR REPLACE SCHEMA Yelp_Reviews;
CREATE OR REPLACE SCHEMA Yelp_Categories;

CREATE OR REPLACE SCHEMA STAGE_DATA;

CREATE OR REPLACE SCHEMA ANALYTICS;

-- Create Tables
CREATE OR REPLACE TABLE YELP_DB.YELP_BUSINESS.YELP_BUSINESS (
	BUSINESS_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR,
    STATE VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    LATITUTE FLOAT,
    LONGITUDE FLOAT,
    STARS FLOAT,
    REVIEW_COUNT INTEGER,
    IS_OPEN INTEGER,
    CATEGORIES VARCHAR(255),
    LOAD_DATETIME TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE YELP_DB.YELP_BUSINESS.YELP_REVIEWS (
	BUSINESS_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR,
    STATE VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    LATITUTE FLOAT,
    LONGITUDE FLOAT,
    STARS FLOAT,
    REVIEW_COUNT INTEGER,
    IS_OPEN INTEGER,
    CATEGORIES VARCHAR(255),
    LOAD_DATETIME TIMESTAMP_LTZ
);
