
USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE YelpAdmin_ROLE;

GRANT ROLE YelpAdmin_ROLE TO ROLE SYSADMIN;
GRANT ROLE YelpAdmin_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE YelpAdmin_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE YelpAdmin_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE YelpAdmin_ROLE;

-- GRANT WRITE PRIVILEGES ON DATABASE OAG_FLIGHT_STATUS_DATA_SAMPLE TO ROLE Flight_ROLE;




-- Databases
CREATE OR REPLACE DATABASE Yelp_DB;
GRANT OWNERSHIP ON DATABASE Yelp_DB TO ROLE YelpAdmin_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE Yelp_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE Yelp_WH TO ROLE YelpAdmin_ROLE;



USE ROLE YelpAdmin_ROLE;
USE WAREHOUSE Yelp_WH;
USE DATABASE Yelp_DB;


-- Schemas
CREATE OR REPLACE SCHEMA Yelp_Business;
CREATE OR REPLACE SCHEMA Yelp_Reviews;
CREATE OR REPLACE SCHEMA Yelp_Categories;

CREATE OR REPLACE SCHEMA STAGE_DATA;

CREATE OR REPLACE SCHEMA ANALYTICS;



