USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE Yelp_ROLE;

GRANT ROLE Yelp_ROLE TO ROLE SYSADMIN;
GRANT ROLE Yelp_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE Yelp_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE Yelp_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE Yelp_ROLE;



-- Databases
CREATE OR REPLACE DATABASE Yelp_DB;
GRANT OWNERSHIP ON DATABASE Yelp_DB TO ROLE Yelp_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE Yelp_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE Yelp_WH TO ROLE Yelp_ROLE;



USE ROLE Yelp_ROLE;
USE WAREHOUSE Yelp_WH;
USE DATABASE Yelp_DB;


CREATE OR REPLACE SCHEMA PA_Restaurants;