name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        pip install fastapi uvicorn pytest pytest-asyncio httpx
        pip install -r requirements.txt
    - name: Run tests
      run: pytest -v -ra --disable-warnings unit_testing.py
